export const T = {
  bg: 'var(--bz-bg)',
  bg2: 'var(--bz-bg2)',
  ink: 'var(--bz-ink)',
  inkDim: 'var(--bz-ink-dim)',
  inkFaint: 'var(--bz-ink-faint)',
  red: 'var(--bz-red)',
  redDark: 'var(--bz-red-dark)',
  yellow: 'var(--bz-yellow)',
  yellowDim: 'var(--bz-yellow-dim)',
  cyan: 'var(--bz-cyan)',
  green: 'var(--bz-green)',
  border: 'var(--bz-border)',
  shadow: 'var(--bz-shadow)',
} as const;
